# Azure App Registration
CLIENT_ID = "efc79e54-d1b2-45b9-b220-c2ace0ed90a4"        # Your Application (client) ID
CLIENT_SECRET = "Hq_8Q~qlGsweN6vve5ArZO.zTHrwPjdLlP1jmcLd"                 # Your client secret
TENANT_ID = "bdeaeda8-c81d-45ce-863e-5232a535b7cb"       # Your Azure tenant ID

# Streamlit redirect URI (must match the one registered in Azure)
REDIRECT_URI = "https://publicpartnerselection.streamlit.app/auth"
#ALLOWED_EMAILS = ["qghd143@leeds.ac.uk"]
